### ISSUE TITLE
Oversimplification or null values in simplifyPolygon method

### ISSUE THREAD

**Issue by geektortoise** [Cytomine-ULiege/Cytomine-core-legacy#20]
Hello, 

At this code, as the numberOfPoint variable is never updated, the simplification is made over and over until the maxLoop value is at 0.
https://github.com/Cytomine-ULiege/Cytomine-core/blob/master/grails-app/services/be/cytomine/utils/geometry/SimplifyGeometryService.groovy#L110

In a same way, if you have a valid polygon with numberOfPoints already between min and max, as it doesn't pass through the loop, the newGeometry object stays at null when it is returned.

If you want, the commit here is cherry-pickable :) 
https://github.com/cytomine/Cytomine-core/commit/b551fd2d3812643358aba364452cf8c8bd99d68c

**Comment by urubens** [comment]
Good catch, thanks
